// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfx1ofKzStPU_SSYz7h3JCTENd9KVYjW8',
    appId: '1:405729119998:web:8e3da2f7b013f156e19faf',
    messagingSenderId: '405729119998',
    projectId: 'fluttershopeappp',
    authDomain: 'fluttershopeappp.firebaseapp.com',
    storageBucket: 'fluttershopeappp.firebasestorage.app',
    measurementId: 'G-43CGQ7QQKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58jhOM6ZZRh-iICkZ4LktBCPkJOEgvSo',
    appId: '1:405729119998:android:485586d465b38c2fe19faf',
    messagingSenderId: '405729119998',
    projectId: 'fluttershopeappp',
    storageBucket: 'fluttershopeappp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LzeIAlXgK7bl0_oajJBqmOo6h8BqzrY',
    appId: '1:405729119998:ios:fa92abf59d43f1ebe19faf',
    messagingSenderId: '405729119998',
    projectId: 'fluttershopeappp',
    storageBucket: 'fluttershopeappp.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5LzeIAlXgK7bl0_oajJBqmOo6h8BqzrY',
    appId: '1:405729119998:ios:fa92abf59d43f1ebe19faf',
    messagingSenderId: '405729119998',
    projectId: 'fluttershopeappp',
    storageBucket: 'fluttershopeappp.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfx1ofKzStPU_SSYz7h3JCTENd9KVYjW8',
    appId: '1:405729119998:web:c3636a8635162a45e19faf',
    messagingSenderId: '405729119998',
    projectId: 'fluttershopeappp',
    authDomain: 'fluttershopeappp.firebaseapp.com',
    storageBucket: 'fluttershopeappp.firebasestorage.app',
    measurementId: 'G-B8WPZCSPR4',
  );
}
